---
- hosts: localhost
  become: yes
  tasks:
    - name: install apache component
      apt: name={{item}} state=present update_cache=yes
      with_items:
      - apache2
      - libapache2-mod-wsgi
      
    - name: enabled mod_wsgi
      apache2_module: name=wsgi state=present
      notify:
      - restart apache2
  
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted  
  
