---
- hosts: all
  become: yes
  tasks:
    - name: Install nginx.      
      package: name={{ item }} state=present
      with_items:
        - nginx
        - nano
        - sshguard
        - curl

    - name: Create website directory
      file: path=/var/www/mywebsite state=directory mode=0755

    - name: Copy nginx config files (main config and vhost config)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: "config/nginx.conf"
          dest: "/etc/nginx/nginx.conf"
        - src: "config/mywebsite.conf"
          dest: "/etc/nginx/conf.d/mywebsite.conf"
        - src: "config/index.html"
          dest: "/var/www/mywebsite/index.html"

    - name: Check if default nginx vhost still exists
      stat: path=/etc/nginx/sites-enabled/default
      register: default_conf

    - name: Remove default nginx vhost configuration
      file: path=/etc/nginx/sites-enabled/default state=absent
      when: default_conf.stat.exists

    - name: Start nginx at boot + make sure it's running right now.
      service: name=nginx state=restarted enabled=yes
